openapi: 3.0.3

info:
  title: Momentum Acquisition API
  version: '1.0.0'
  description: API to manage momentum.

servers:
  - url: 'http://localhost:8080/'

paths:
  /processes:
    get:
      tags:
        - Process
      operationId: getProcesses
      summary: Get list of processes
      description: Returns a JSON array of processes.
      responses:
        '200':
          description: Successfully returned the list of processes.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Process'

components:
  schemas:
    Process:
      type: object
      required:
        - pid
        - name
        - path
        - cpu
        - memory
        - threads
      properties:
        pid:
          type: integer
          description: Unique identifier for the process.
          example: 1234
        name:
          type: string
          description: Name of the executable process.
          example: 'chrome.exe'
        path:
          type: string
          description: Full path of the executable process.
          example: 'C:\\Program Files\\Google\\Chrome\\chrome.exe'
        cpu:
          type: number
          format: double
          description: Percentage of CPU usage by the process.
          example: 12.5
        memory:
          type: integer
          description: Amount of memory used in KB.
          example: 256000
        threads:
          type: integer
          description: Number of threads associated with the process.
          example: 18
  