openapi: 3.0.3

info:
  title: Momentum Acquisition API
  version: '1.0.0'
  description: API to manage momentum.

servers:
  - url: 'http://localhost:8080/'

paths:
  /processes:
    get:
      tags:
        - Process
      operationId: getProcesses
      summary: Get list of processes
      description: Returns a JSON array of processes.
      responses:
        '200':
          description: Successfully returned the list of processes.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Process'

components:
  schemas:
    Process:
      type: object
      required:
        - pid
        - name
        - path
        - cpu
        - memory
        - threads
      properties:
        pid:
          type: integer
        name:
          type: string
        path:
          type: string
        cpu:
          type: number
          format: double
        memory:
          type: integer
        threads:
          type: integer